export { KoreaAdministrativeMap } from "./components/KoreaAdministrativeMap.js";
export {
  DEFAULT_VIEWPORT,
  MAP_HEIGHT,
  MAP_MAX_ZOOM,
  MAP_WIDTH,
  applyViewportScreenOffset,
  areViewportsEqual,
  clampZoom,
  getFocusForFeature,
  removeViewportScreenOffset,
  topologyToRegions,
} from "./lib/geometry.js";
export { getDefaultSidoLabel, getSidoLabelOffset } from "./lib/labels.js";
export {
  createAssetBoundaryLoaders,
  fetchBoundaryCollection,
  loadRegionsMetadata,
} from "./lib/loaders.js";
export {
  DEFAULT_CHOROPLETH_PALETTE,
  buildChoroplethLegendItems,
  getChoroplethColor,
  getChoroplethValues,
  resolveChoroplethDomain,
} from "./lib/choropleth.js";
export { DEFAULT_THEME, DEFAULT_UI_LABELS, mergeTheme, mergeUiLabels } from "./lib/theme.js";
export type {
  BoundaryTopology,
  GeographyStyleOverride,
  GeographyStyleState,
  KoreaAdministrativeMapProps,
  KoreaAdministrativeMapRenderApi,
  KoreaMapBaseLabelOptions,
  KoreaMapChoroplethLevel,
  KoreaMapChoroplethOptions,
  KoreaMapDepth,
  KoreaMapDrilldownOptions,
  KoreaMapHoveredRegion,
  KoreaMapLabelOptions,
  KoreaMapLoaders,
  KoreaMapLegendItem,
  KoreaMapOverlayPosition,
  KoreaMapRegionColorMap,
  KoreaMapRegionFillOptions,
  KoreaMapRegionValueMap,
  KoreaMapSelection,
  KoreaMapSelectableDepth,
  KoreaMapSggLabelOptions,
  KoreaMapSidoLabelOptions,
  KoreaMapStrokeLevelOptions,
  KoreaMapStrokeOptions,
  KoreaMapTheme,
  KoreaMapTooltipContext,
  KoreaMapTooltipOptions,
  KoreaMapUiLabels,
  KoreaMapZoomOptions,
  KoreaRegionsDataset,
  LoadBoundaryOptions,
  MapViewport,
  RegionCollection,
  RegionFeature,
  RegionFeatureProperties,
  RegionLabelRenderContext,
  RegionStyleContext,
  RegionLevel,
  SggRegionSummary,
  SidoRegionSummary,
  ViewportScreenOffset,
} from "./types.js";
